parameters:
  - name: environment
    type: string
  - name: subscription
    type: string

stages:
  - stage: Build${{ parameters.environment }}
    displayName: "${{ parameters.environment }} Build"
    pool:
      vmImage: 'ubuntu-latest'
    ${{ if eq(parameters.environment, 'prod') }}:
      dependsOn: Wait${{ parameters.environment }}
    ${{ else }}:
      dependsOn: Plan${{ parameters.environment }}
    variables:
      - group: PIP-APIM-BUILD-${{ parameters.environment }}
      - template: ../variables/${{ parameters.environment }}.yaml
    jobs:
    - template: ../jobs/terraform-apply.yaml
      parameters:
        displayName: Build ${{ parameters.environment }}
        subscription: ${{ parameters.subscription }}